name: "Action on delete"

on: [delete, push]

jobs:
  triage:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
    steps:
    - name: tr
      run: echo ${{ env.BRANCH_NAME }} | tr / -
    - name: new
      run: echo "BRANCH=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
    - name: echo
      run: echo ${{ env.BRANCH }}
