name: "Action on delete"

on: [delete, push]

jobs:
  triage:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      run: echo $ {{ BRANCH_NAME }}
      with:
        submodules: recursive
        fetch-depth: 0
