name: "Action on delete"

on: delete

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name
      run: echo "BRANCH=$(echo ${{ github.head_ref || github.ref_name }} | tr / -)" >> $GITHUB_ENV
    - name: echo
      run: echo ${{ env.BRANCH }}
    - name: Get event branch name
      run: echo "DELETE_BRANCH=$(echo ${{ github.event.ref }} | tr / -)" >> $GITHUB_ENV
    - name: echo
      run: echo ${{ env.DELETE_BRANCH }}
