name: Docker Image CI/CD

on:
  push:
    branches: [main]

jobs:
  docker-image-ci:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Create shot SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: docker/Dockerfile
          tags: |
            ghcr.io/aiden-jeon/github-cicd:latest
            ghcr.io/aiden-jeon/github-cicd:${{ steps.short-sha.outputs.sha }}

