name: Generate Version

on:
  push:
    branches: [main]

jobs:
  generate-version:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make variable
        id: variable
        run: |
          VERSION=1.0.0
          echo '::set-output name=VERSION::1.0.0'
      - name: echo
        run: |
          echo "${{ steps.variable.outputs.VERSION }}"
