name: Generate Version

on:
  push:
    branches: [main]

jobs:
  docker-image-ci:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: variable
        run: |
          VERSION=1.0.0
      - name: echo
        run: |
          echo ${{ steps.variable.outputs.VERSION }}
